import { Component, signal, computed, inject, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EbslService } from '../services/ebsl.service';

@Component({
  selector: 'app-cathexis',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="max-w-5xl mx-auto py-8 px-4">
      <div class="mb-10">
        <h2 class="text-3xl font-bold text-white mb-2">CATHEXIS Layer</h2>
        <p class="text-slate-400 max-w-2xl">
          Humans don't read tensors. They read labels. Cathexis uses an LLM-driven process to map high-dimensional trust embeddings into semantic handles.
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <!-- Input Simulation -->
        <div class="bg-slate-800/30 border border-slate-700 rounded-2xl p-8">
          <h3 class="text-lg font-bold text-white mb-6">1. Trust Embedding Source</h3>
          
          <div class="space-y-6">
            <div>
              <label class="block text-sm text-slate-400 mb-2">Simulate Network Activity</label>
              <div class="flex gap-2">
                 <button (click)="setProfile('new')" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm transition-colors">New User</button>
                 <button (click)="setProfile('good')" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm transition-colors">Power User</button>
                 <button (click)="setProfile('bad')" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm transition-colors">Sybil/Bot</button>
                 <button (click)="setProfile('mixed')" class="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded text-sm transition-colors">Controversial</button>
              </div>
            </div>

            <div class="p-4 bg-black/20 rounded-lg font-mono text-xs text-slate-400 border border-slate-700/50">
              <div class="mb-2 text-indigo-400 font-bold">Input Vector <b>x</b><sub>i</sub>(t)</div>
              <div class="break-all leading-relaxed opacity-70">
                [0.{{r()}}4, 0.{{s()}}1, 0.9{{r()}}, 0.02, 0.{{r()+s()}}, ... 128_dim_float]
              </div>
              <div class="mt-3 flex gap-4 text-slate-500">
                <span>r: {{r()}}</span>
                <span>s: {{s()}}</span>
                <span>u: {{ (2/(r()+s()+2)).toFixed(2) }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Output Card -->
        <div class="relative">
          <div class="absolute inset-0 bg-gradient-to-br from-amber-500/10 to-orange-600/10 rounded-2xl blur-xl"></div>
          <div class="relative bg-slate-900 border border-slate-800 rounded-2xl p-8 h-full flex flex-col justify-center items-center text-center">
            
            <div class="mb-6">
              <div class="text-xs font-bold tracking-widest text-amber-500 uppercase mb-2">Cathexis Handle</div>
              @if (currentLabel(); as label) {
                <div [class]="'px-6 py-3 rounded-full border text-lg font-bold shadow-lg animate-in zoom-in duration-300 ' + label.style">
                  {{ label.handle }}
                </div>
              }
            </div>

            @if (currentLabel(); as label) {
              <p class="text-slate-300 italic mb-6 animate-in fade-in slide-in-from-bottom-2 duration-500 delay-100">
                "{{ label.gloss }}"
              </p>
            }

            <div class="text-xs text-slate-600 font-mono">
              Generated by Cathexis Categoriser + LLM
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class CathexisComponent {
  ebsl = inject(EbslService);
  r = signal(0);
  s = signal(0);

  currentLabel = computed(() => this.ebsl.getCathexisLabel(this.r(), this.s()));

  setProfile(type: 'new' | 'good' | 'bad' | 'mixed') {
    switch(type) {
      case 'new': this.r.set(0); this.s.set(0); break;
      case 'good': this.r.set(55); this.s.set(1); break;
      case 'bad': this.r.set(12); this.s.set(40); break;
      case 'mixed': this.r.set(35); this.s.set(32); break;
    }
  }
}